In [3]:
import pandas as pd

# Read the CSV file
df = pd.read_csv("new_combined.csv")

# Display the contents of the DataFrame
df.head()

,id,time,amplitude1_1,amplitude2_1,amplitude3_1,amplitude4_1,amplitude5_1,amplitude6_1,amplitude7_1,amplitude8_1,...,phase58_2,phase59_2,phase60_2,phase61_2,phase62_2,phase63_2,phase64_2,rssi_1,rssi_2,activity
0,368,10:16:40,118.726577,5.0,28.635642,30.805844,32.015621,32.893768,31.780497,30.886890,...,1.467715,1.532354,1.527345,1.515298,1.418147,1.212026,0.643501,-51,-48,4
1,369,10:16:40,118.726577,5.0,29.000000,31.144823,32.649655,32.202484,31.906112,30.413813,...,-2.944197,-2.922924,-2.886410,-2.934096,-2.999696,3.017238,2.356194,-51,-48,4
2,370,10:16:40,118.726577,5.0,29.154759,31.384710,32.449961,33.421550,32.557641,31.144823,...,-1.945130,-1.904041,-1.905533,-1.941688,-2.003204,-2.356194,-2.999696,-51,-48,4
3,371,10:16:40,118.726577,5.0,22.090722,24.020824,25.000000,25.079872,24.331050,23.537205,...,2.572279,2.594804,2.601173,2.582993,2.512796,2.191046,1.570796,-51,-48,4
4,372,10:16:40,118.726577,5.0,29.832868,31.780497,32.557641,33.136083,32.015621,31.064449,...,-2.910502,-2.889038,-2.853537,-2.875341,-2.966920,3.058451,2.622447,-51,-48,4

In [4]:
X = df.iloc[:, 2:66]

In [5]:
X.head()

,amplitude1_1,amplitude2_1,amplitude3_1,amplitude4_1,amplitude5_1,amplitude6_1,amplitude7_1,amplitude8_1,amplitude9_1,amplitude10_1,...,amplitude55_1,amplitude56_1,amplitude57_1,amplitude58_1,amplitude59_1,amplitude60_1_1,amplitude61_1,amplitude62_1,amplitude63_1,amplitude64_1
0,118.726577,5.0,28.635642,30.805844,32.015621,32.893768,31.780497,30.886890,28.844410,27.018512,...,31.906112,31.384710,30.886890,29.068884,26.832816,24.186773,21.633308,20.518285,20.000000,20.124612
1,118.726577,5.0,29.000000,31.144823,32.649655,32.202484,31.906112,30.413813,28.231188,26.248809,...,31.016125,31.064449,30.149627,28.160256,26.172505,24.083189,21.000000,19.235384,19.313208,20.591260
2,118.726577,5.0,29.154759,31.384710,32.449961,33.421550,32.557641,31.144823,28.600699,26.076810,...,31.575307,31.400637,30.265492,28.160256,26.172505,23.194827,20.615528,19.697716,19.416488,21.213203
3,118.726577,5.0,22.090722,24.020824,25.000000,25.079872,24.331050,23.537205,22.135944,19.697716,...,24.041631,23.345235,22.671568,21.260292,19.849433,17.691806,16.278821,14.422205,14.866069,15.297059
4,118.726577,5.0,29.832868,31.780497,32.557641,33.136083,32.015621,31.064449,29.274562,26.925824,...,32.249031,31.384710,30.528675,28.844410,27.459060,24.698178,22.360680,21.189620,21.213203,21.000000

In [6]:
import pandas as pd
import numpy as np

def remove_outliers(subcarrier_series, window_size=5, threshold=3):
        filtered_series = subcarrier_series.copy()
        for i in range(window_size, len(subcarrier_series)):
            window_data = subcarrier_series[i-window_size:i]
            mean = window_data.mean()
            std = window_data.std()
            if abs(subcarrier_series[i] - mean) > threshold * std:
                filtered_series[i] = subcarrier_series[i-1]
        return filtered_series

In [7]:
subcarriers_filtered = X.apply(lambda x: remove_outliers(x))

In [ ]:
subcarriers_filtered.head()